export const routes = {
	HOME: '/',
	DASHBOARD: '/dashboard',
	PROFILE: '/profile',
	FORMS: {
		ROOT: '/forms',
		BABY: '/baby',
		ADULT: '/adult',
	},
	LOGIN: '/login',
	REGISTER: '/register',
	VACCINE: {
		TYPES: '/vaccine-types',
		BATCH: '/vaccine-batches',
		QUEUE: '/vaccine-queues',
		ROOT: '/vaccines',
	},
	INCOMING: {
		RESIDENTS: '/incoming-residents',
		ELIGIBILITY: '/incoming-eligibility',
		RECOMMENDATION: '/incoming-recommendation',
		APPOINTMENT: '/incoming-appointment',
	},
	DATES: '/available-dates',
	PATIENT: '/patient',
	QUESTIONS: '/questions',
	FAQS: '/faqs',
	ANNOUNCEMENTS: '/announcements',
	HEALTH_WORKERS: '/health-workers',
	PATIENTS: '/patients',
	ECCD: '/eccd',
	RECORDS: '/records',
};
